### ISSUE TITLE
Don't commit generated code in the Git repo?

### ISSUE THREAD

**Issue by dbolkensteyn** [stylianos-agapiou-sonarsource/sonar-solidity#86]
The following files in the frontend seem to be generated by ANTLR:
* https://github.com/stylianos-agapiou-sonarsource/sonar-solidity/blob/master/solidity-frontend/src/main/java/org/sonarsource/solidity/frontend/SolidityParser.java
* https://github.com/stylianos-agapiou-sonarsource/sonar-solidity/blob/master/solidity-frontend/src/main/java/org/sonarsource/solidity/frontend/SolidityLexer.java

From a formal grammar stored in a file called Solidity.g4.

Adding generated code to the Git repository is usually a bad idea because of several reasons:
1. It is unreadable code
2. Nobody should actually make changes to it, because otherwise, if the Solidity language evolves and a new version of Solidity.g4 becomes available, then it will be a nightmare to manually merge the changes back into the newly re-generated parser and lexer.

It seems that ANTLR has a Maven plugin to generate those files in a temporary way, during the build. Have a look at http://www.antlr.org/api/maven-plugin/latest/usage.html

And of course, if you do that, then I would expect to find this Solidity.g4 file persisted in this repository, which I currently do not :)

**Comment by stylianos-agapiou-sonarsource** [comment]
Thanks a lot for pointing this issue!

As you can see the commit below fixes the issue: https://github.com/stylianos-agapiou-sonarsource/sonar-solidity/commit/43cc7544df9dc71cd916cf8359c8edd120e3984b

You can also find the corresponding grammar here: https://github.com/stylianos-agapiou-sonarsource/sonar-solidity/blob/master/solidity-frontend/src/main/antlr4/org/sonarsource/solidity/frontend/Solidity.g4

**Comment by dbolkensteyn** [comment]
👍  `696 additions and 13,434 deletions` those are nice PRs ;)
